Implements an option to toggle private messages
cloudnode-pro/CloudnodeMSG pull request #26
Opened 2024-01-10 22:29 UTC by Dviih

This pull request implements an option for players to opt to use or not private messages.

The following permissions were created for this addition:
- `cloudnodemsg.toggle` -> Gives permission to player to use `/togglemsg`.
- `cloudnodemsg.toggle.other` -> Gives permission to player to change the toggle status of other players using `/togglemsg <player>`.
- `cloudnodemsg.toggle.bypass` -> Any player with this permission can send a private message regardless of the recipient toggle status.

In `Message` there are three methods that this pull request implements:
- `incomeEnable` -> Enables private messages for the player.
- `incomeDisable` -> Disables private messages for the player.
- `isIncomeEnabled` -> Returns a boolean of the status of the player's toggled option.

The command implementation is inside the class `ToggleMessageCommand`.

2024-01-10 22:44 UTC, km127pl approved these changes
looks good to me

2024-01-11 14:50 UTC, zefir-git requested changes

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
> +
should be like `toggle.enable` etc.

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
> +import pro.cloudnode.smp.cloudnodemsg.error.*;
this should be reverted. see here to disable this: https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
> +     * The player you disabled private messages
"player you *wanted to message*" perhaps (same for the one below)

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
> +public class ToggleMessageCommand extends Command {
```suggestion
public final class ToggleMessageCommand extends Command {
```

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
> +    public static final @NotNull String usage = "<player>";
this is not really needed here as the player arg is optional

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
> +        return null;
if has permission OTHER return null, else return empty array

`null` means list of all online players is returned

2024-01-11 14:50 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
> +    }
these should be `incoming` instead of `income`

2024-01-11 14:50 UTC, zefir-git commented on src/main/resources/config.yml
> +
as mentioned earlier, it would be best to put these like
```yaml
toggle:
    disable: …
```

I think the messages can be improved, here are my ideas:

```xml
<yellow>(!) You've disabled private messages. Run again to re-enable.</yellow>
<green>(!) Disabled private messages for <gray><player></gray>.</green>
<green>(!) You can now receive private messages again.</green>
<green>(!) Re-enabled private messages for <gray><player></gray>.</green>
```

2024-01-11 14:50 UTC, zefir-git commented on src/main/resources/config.yml
> +    incoming-disabled: "<red>(!) <gray><player></gray> has disabled their private messages."
```suggestion
    incoming-disabled: "<red>(!) You cannot message <gray><player></gray> because they have disabled private messages.</red>"
```

2024-01-12 12:30 UTC, Dviih commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ReplyCommand.java
> +import pro.cloudnode.smp.cloudnodemsg.error.*;
This was done automatically by the IDE so I thought I could keep it, Do you know how to not allow it?

2024-01-15 12:26 UTC, Dviih commented on src/main/resources/config.yml
> +
783bc3e69d0c4bb1b956f79e415facc6843e04d4

2024-01-15 12:26 UTC, Dviih commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/message/Message.java
> +    }
20a76cf37372cc5d529b39d1c8e84d4379ec6847

2024-01-15 12:27 UTC, Dviih commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/PluginConfig.java
> +
783bc3e69d0c4bb1b956f79e415facc6843e04d4

2024-01-15 13:13 UTC, zefir-git commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
> +        return null;
good like this, don't think anything more needs to be added here

2024-01-15 13:24 UTC, zefir-git submitted a review, later dismissed

2024-01-15 16:00 UTC, Dviih commented on src/main/java/pro/cloudnode/smp/cloudnodemsg/command/ToggleMessageCommand.java
> +                return true;
75774f6429c416f0d8527637ae97ebbcd02437d8

2024-01-15 16:02 UTC, zefir-git approved these changes

2024-01-15 16:04 UTC, merged